project:
  type: book
  output-dir: docs
  resources:
    - /webr-serviceworker.js
    - /webr-worker.js
    - /data

filter: webr

book:
  title: "A Practical Introduction to Regression Modeling in R"
  author: "Wesley Brooks"
  date: last-modified
  date-format: D MMMM, YYYY
  search: true
  repo-url: https://github.com/ucdavisdatalab/workshop_regression
  
  chapters:
    - index.qmd
    - 01_introduction.qmd
    - 02_linear_model.qmd
    - 03_categorical_continuous.qmd
    - 04_generalized_linear_model.qmd
    - 05_fixed_random_effects.qmd
    #- 06_conclusion.qmd
  
  sidebar:
    logo: https://datalab.ucdavis.edu/wp-content/uploads/2019/07/datalab-logo-full-color-rgb-1.png
  
  site-url: https://d-rug.github.io

format:
  html:
    theme: cosmo
    number-sections: true
  
